version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    networks:
      - app-network
    volumes:
      - lab-10-deployment:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    image: node:14
    user: root
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - ./:/home/node/app
    command: 'npm start'
  test:
    image: node:14
    user: root
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=test
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./:/home/node/app
    command: ['sh', '-c', './wait-for-it.sh db 5432 -- npm test']

networks:
  app-network:
    driver: bridge

volumes:
  lab-10-deployment:
